version: 2.1

commands:
  install_openjdk_11:
    description: "Install OpenJdk 11"
    steps:
      - run: wget https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz -O ~/openjdk-11.tar.gz
      - run: tar xvf ~/openjdk-11.tar.gz -C ~/
      - run: sudo mv ~/jdk-11.0.2 /usr/local/openjdk-11
      - run: mkdir ~/.m2
      - run: |
          cat > ~/.m2/toolchains.xml \<< EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 http://maven.apache.org/xsd/toolchains-1.1.0.xsd">
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>1.8</version>
                <vendor>openjdk</vendor>
                <id>openjdk-1.8</id>
              </provides>
              <configuration>
                <jdkHome>/usr/local/openjdk-8</jdkHome>
              </configuration>
            </toolchain>
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>11</version>
                <vendor>openjdk</vendor>
                <id>openjdk-11</id>
              </provides>
              <configuration>
                <jdkHome>/usr/local/openjdk-11</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          EOF

  std_mvnw:
    description: "Standard mvnw steps"
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-dependencies-{{ checksum "pom.xml" }}
            - m2-dependencies-
      - run: ./mvnw -Pcicd clean install -DskipTests
      - run: ./mvnw -Pcicd test
      - run:
          name: "Coveralls"
          command: ./mvnw -Pcicd,qa_jacoco -DCOVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} verify jacoco:report coveralls:report
          when: on_success
      - run: export JAVA_HOME=/usr/local/openjdk-11 && export PATH=${JAVA_HOME}/bin:{$PATH} && ./mvnw -Pcicd test
      - run:
          name: "Tidy Cache before save"
          command: rm -rf ~/.m2/repository/com/github/nhojpatrick
          when: always
      - save_cache:
          key: m2-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository
            - ~/.m2/wrapper
          when: always

  qa_checkstyle:
    description: "Standard mvnw checkstyle"
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-dependencies-{{ checksum "pom.xml" }}-checkstyle
            - m2-dependencies-{{ checksum "pom.xml" }}
            - m2-dependencies-
      - run: ./mvnw -Pcicd,qa_checkstyle -DskipTests verify
      - run:
          name: "Tidy Cache before save"
          command: rm -rf ~/.m2/repository/com/github/nhojpatrick
          when: always
      - save_cache:
          key: m2-dependencies-{{ checksum "pom.xml" }}-checkstyle
          paths:
            - ~/.m2/repository
            - ~/.m2/wrapper
          when: always

  qa_javadoc:
    description: "Standard mvnw javadoc"
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-dependencies-{{ checksum "pom.xml" }}-javadoc
            - m2-dependencies-{{ checksum "pom.xml" }}
            - m2-dependencies-
      - run: ./mvnw -Pcicd,qa_javadoc -DskipTests verify
      - run:
          name: "Tidy Cache before save"
          command: rm -rf ~/.m2/repository/com/github/nhojpatrick
          when: always
      - save_cache:
          key: m2-dependencies-{{ checksum "pom.xml" }}-javadoc
          paths:
            - ~/.m2/repository
            - ~/.m2/wrapper
          when: always

  qa_pmd:
    description: "Standard mvnw pmd"
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-dependencies-{{ checksum "pom.xml" }}-pmd
            - m2-dependencies-{{ checksum "pom.xml" }}
            - m2-dependencies-
      - run: ./mvnw -Pcicd,qa_pmd -DskipTests verify
      - run:
          name: "Tidy Cache before save"
          command: rm -rf ~/.m2/repository/com/github/nhojpatrick
          when: always
      - save_cache:
          key: m2-dependencies-{{ checksum "pom.xml" }}-pmd
          paths:
            - ~/.m2/repository
            - ~/.m2/wrapper
          when: always

  qa_spotbugs:
    description: "Standard mvnw spotbugs"
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-dependencies-{{ checksum "pom.xml" }}-spotbugs
            - m2-dependencies-{{ checksum "pom.xml" }}
            - m2-dependencies-
      - run: ./mvnw -Pcicd,qa_spotbugs -DskipTests verify
      - run:
          name: "Tidy Cache before save"
          command: rm -rf ~/.m2/repository/com/github/nhojpatrick
          when: always
      - save_cache:
          key: m2-dependencies-{{ checksum "pom.xml" }}-spotbugs
          paths:
            - ~/.m2/repository
            - ~/.m2/wrapper
          when: always

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - install_openjdk_11
      - std_mvnw

  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - std_mvnw

  jdk13:
    docker:
      - image: circleci/openjdk:13-jdk-buster
    steps:
      - std_mvnw

  jdk14:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    steps:
      - std_mvnw

  checkstyle:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - install_openjdk_11
      - qa_checkstyle

  javadoc:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - install_openjdk_11
      - qa_javadoc

  pmd:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - install_openjdk_11
      - qa_pmd

  spotbugs:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - install_openjdk_11
      - qa_spotbugs

workflows:
  version: 2
  build_all:
    jobs:
      - jdk8
      - checkstyle
      - javadoc
      - pmd
      - spotbugs
      #- jdk11
      #- jdk13
      #- jdk14
